version: "2"
services:
    client:
        stdin_open: true
        build:
            context: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        depends_on: 
            - api
        links:
            - api
    api:
        build:
            context: ./api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
