version: '3'
services:
  web-app:
    stdin_open: true
    tty: true
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: web-app
  to-do-api:
    build: ./api
    ports:
      - '9000:9000'
    restart: on-failure
    container_name: to-do-api
    volumes:
      - /app/node_modules # Inside the container, don't try to 